networks:
  default:

services:
  iperf:
    image: ghcr.io/routerzero/iperf-server:latest
    deploy:
      restart_policy:
        condition: any
    cap_drop:
      # Drop all capabilities that are not needed
      - FSETID
      - KILL
      - SETPCAP
      - NET_RAW
      - SYS_CHROOT
      - MKNOD
      - AUDIT_WRITE
      - SETFCAP
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Stockholm
    ports:
      # 5001 is default for iperf 2, and 5201 is default for iperf 3. Only one is needed at a time.
      - "5001:5001/TCP"
      - "5201:5201/TCP"
    networks:
      default: