#!/command/with-contenv bash
# shellcheck shell=bash

# svc-iperfd main
main() {
    if [ -x "/usr/bin/iperf3" ]; then
        /command/s6-setuidgid "${PUID}:${PGID}" /usr/bin/iperf3 --server "${@}"
        return
    fi

    /command/s6-setuidgid "${PUID}:${PGID}" /usr/bin/iperf --server "${@}"
}
main "${@}"
