#!/command/with-contenv bash
# shellcheck shell=bash

# svc-iperfd main
main() {
    # This will prepend service name to all output from here
    exec > >(while read -r line; do printf "[svc-iperfd] %s\n" "${line}"; done) 2>&1

    exec /usr/bin/iperf --server "${@}"
}
main
